{
	"version": 1615645818,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/ground-sheet0.png",
		"images/donut-sheet0.png",
		"images/obstacle_2-sheet0.png",
		"images/obstacle_2-sheet1.png",
		"images/obstacle_2-sheet2.png",
		"images/obstacle-sheet0.png",
		"images/obstacle-sheet1.png",
		"images/monster-sheet0.png",
		"images/monster-sheet1.png",
		"images/sprite2-sheet0.png",
		"images/background-sheet0.png",
		"images/lvls-sheet0.png",
		"images/lvls-sheet1.png",
		"images/star-sheet0.png",
		"images/addforecer-sheet0.png",
		"images/play-sheet0.png",
		"images/music-sheet0.png",
		"images/music-sheet1.png",
		"images/sounds-sheet0.png",
		"images/sounds-sheet1.png",
		"images/winorlosebackground-sheet0.png",
		"images/winorlosepanel-sheet0.png",
		"images/winstar-sheet0.png",
		"images/winstar-sheet1.png",
		"images/reload-sheet0.png",
		"images/next_level-sheet0.png",
		"images/losereload-sheet0.png",
		"images/musics-sheet0.png",
		"images/sound23-sheet0.png",
		"images/starunderlevel-sheet0.png",
		"images/storebutton-sheet0.png",
		"images/backbutton-sheet0.png",
		"images/toppart-sheet0.png",
		"images/downpart_store-sheet0.png",
		"images/gold-sheet0.png",
		"images/candy-sheet0.png",
		"images/bomb-sheet0.png",
		"images/staronmainscene-sheet0.png",
		"images/staronmainscene-sheet1.png",
		"images/help-sheet0.png",
		"images/win_trigger-sheet0.png",
		"images/white_bg-sheet0.png",
		"images/home-sheet0.png",
		"images/particles2.png",
		"images/particles4.png",
		"images/particles5.png",
		"images/particles3.png",
		"images/particles6.png",
		"images/candy_error-sheet0.png",
		"images/help_win-sheet0.png",
		"images/help_close-sheet0.png",
		"images/help_bg-sheet0.png",
		"images/help_text-sheet0.png",
		"images/logo-sheet0.png",
		"images/monster_eye-sheet0.png",
		"images/monster_eye-sheet1.png",
		"images/obstacle_destroy_particle.png",
		"images/jelly-sheet0.png",
		"images/black_alpha-sheet0.png",
		"images/data_controller-sheet0.png",
		"images/candy_reward-sheet0.png",
		"images/candy_reward_text.png",
		"images/obstacle_3-sheet0.png",
		"images/obstacle_3_pipe-sheet0.png",
		"images/cake_bomb_particle.png",
		"media/star coll.m4a",
		"media/star coll.ogg",
		"media/music 2.m4a",
		"media/music 2.ogg",
		"media/blocks.m4a",
		"media/blocks.ogg",
		"media/buttons 1.m4a",
		"media/buttons 1.ogg",
		"media/buttons.m4a",
		"media/buttons.ogg",
		"media/jelly.m4a",
		"media/jelly.ogg",
		"media/not enough coin.m4a",
		"media/not enough coin.ogg",
		"media/win music.m4a",
		"media/win music.ogg",
		"media/set_candy.m4a",
		"media/set_candy.ogg",
		"media/chewing_2.m4a",
		"media/chewing_2.ogg",
		"media/yeahhhh.m4a",
		"media/yeahhhh.ogg",
		"media/bomb 2.ogg",
		"media/bomb 2.m4a",
		"media/06 moonlight.m4a",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"1.png",
		"2.png"
	]
}